# Generated by Django 4.2.19 on 2025-06-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('generation', models.IntegerField()),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True)),
                ('joined_at', models.DateField()),
                ('graduated_at', models.DateField(blank=True, null=True)),
                ('fan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('penlight_color_1', models.CharField(max_length=50)),
                ('penlight_color_2', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agency')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('blog', 'Blog'), ('instagram', 'Instagram'), ('message', 'Message App')], max_length=20)),
                ('url', models.URLField()),
                ('hashtag', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='CallName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_names', to='api.member')),
            ],
        ),
    ]
