# Generated by Django 4.2.19 on 2025-06-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tver',
            options={'verbose_name': 'TVer', 'verbose_name_plural': 'TVers'},
        ),
    ]
