# Generated by Django 4.2.19 on 2025-06-15 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tver_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tver',
            old_name='is_deleted',
            new_name='delete_flg',
        ),
        migrations.RemoveField(
            model_name='member',
            name='delete_flg',
        ),
        migrations.AddField(
            model_name='agency',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='callname',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallink',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
