# Generated by Django 4.2.19 on 2025-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_deleted_tver_delete_flg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_deleted',
            new_name='delete_flg',
        ),
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='callname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
